### ISSUE TITLE
Convert State-Action Mapping

### ISSUE THREAD

**Issue by modass** [modass/simplex-architectures#7]
We need to convert a sequence of actions (#5) to a state-action mapping (#6). 

**Input:** A sequence of actions
**Output:** none

**Idea**
Simulate using the simulator, extract intermediate state sets, add them to the described data structure.

**Comment by bmaderbacher** [comment]
The action sequence simulator (#9) can provide a vector of (Location, State-Set, Action) for a valid action sequence. It still needs to be integrated with the state-action mapping data structure (#6).

**Comment by modass** [comment]
Okay, let me know what the state is, I can take a look
