### ISSUE TITLE
Heuristic for Determining Action Sequences

### ISSUE THREAD

**Issue by modass** [modass/simplex-architectures#8]
Create some heuristics that proposes meaningful state-action sequences to enhance the base controller.

**Idea**
- Random selection of actions
- Targeted selection (mutation), "Select similar action as the action associated with a close set"
- Genetic search, measure distance to target set and use evolutionary approach to optimize action sequence

**Comment by bmaderbacher** [comment]
I have added (#9 ) a template based "exhaustive" search. It is slow, but works reasonably well.
